runtime: nodejs20

env_variables:

  CLIENT_ID: "2f4890336ee5856d21bb"
  CLIENT_SECRET: "9e60a60eae1d5939b66090df99ccb4f5"
  MONGO_URI: "mongodb+srv://paraspanchal555:MOem5VDWHxFlvKMD@webtech.zycr3.mongodb.net/?retryWrites=true&w=majority&appName=WebTech"
  

manual_scaling:
  instances: 1